version: '3.1'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  grafana:
    image: grafana/grafana:4.6.1
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: changeme
    volumes:
      - gfdata:/var/lib/grafana:/var/lib/grafana

volumes:
  esdata:
    driver: local
  gfdata:
    driver: local
